source 'http://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'selenium-webdriver'
gem 'watir-webdriver'
gem 'require_all'
gem 'activesupport', '4.1.8'
gem 'rake'
gem 'simplecov'
gem 'simplecov-rcov'
gem 'ci_reporter'
#comment to test if change fires build
# gem to connect to saucelabs and also dynamically change browser parameters
gem 'saucelabs'

gem 'nokogiri'





